In [1]:
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

#  First steps with
<img src="https://pytorch.org/docs/stable/_static/pytorch-logo-dark.svg" width=800/>

## What is PyTorch ?
It’s a Python-based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides maximum flexibility and speed


### PyTorch is deeply integrated into Python
- imperative programming: access and print variables anytime (those who tried tensorflow, keras, etc will appreciate :) )
- use python's usual debuging tools (same here :) )
- easily integrate with numpy, scipy, pandas, sklearn, etc

## Tensors and NumPy arrays
- Tensors $\sim$ numpy N-dimensinal arrays
  - Can be 0-dimensional (scalars)
  - Support for sparse tensors included
  - intentionally similar API: same function names and indexing, slicing and broadcasting conventions
- Tensors are loadable on GPU

<center>
    <img src="https://github.com/pytorch/pytorch/raw/master/docs/source/_static/img/tensor_illustration.png"
         width=800/>
    Source: https://github.com/pytorch/pytorch
</center>
  

**On Numpy**

In [2]:
import numpy as np
a = np.arange(5, dtype=np.int32)
b = 2*a   
a, b

(array([0, 1, 2, 3, 4], dtype=int32), array([0, 2, 4, 6, 8], dtype=int32))

**On torch**

In [3]:
import torch
a = torch.arange(5, dtype=torch.int32)
b = 2*a  
a, b

(tensor([0, 1, 2, 3, 4], dtype=torch.int32),
 tensor([0, 2, 4, 6, 8], dtype=torch.int32))

**In-place operations**
All in-place operators available as methods on tensor with `_` ending

In [4]:
  a

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [5]:
a.add_(1)  # in-place methods return self

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
a.sub_(1).mul_(2) # so we can chain them

tensor([0, 2, 4, 6, 8], dtype=torch.int32)

In [7]:
a.eq_(a)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)

In [8]:
a = torch.arange(5, dtype=torch.int32)

### Easy conversion between frameworks
- shared memeory between numpy arrays and cpu tensors

In [9]:
a_numpy = a.numpy()
a_numpy += 1  # torch tensor a will also be modified
print("torch: ", a, 
      "\nnumpy: ",a_numpy)

torch:  tensor([1, 2, 3, 4, 5], dtype=torch.int32) 
numpy:  [1 2 3 4 5]


* create tensor from numpy array

In [10]:
a_numpy2tensor = torch.from_numpy(a_numpy)
a_numpy2tensor += 1  # numpy array will also be modified
print("torch: ", a_numpy2tensor, 
      "\nnumpy: ",a_numpy)

torch:  tensor([2, 3, 4, 5, 6], dtype=torch.int32) 
numpy:  [2 3 4 5 6]


### An operation on GPU
First let's time it on cpu

In [11]:
N = 1000
a = np.random.rand(N,N).astype(np.float32)
x = np.arange(N, dtype=np.float32)
%timeit y = a*x

882 µs ± 162 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
N = 1000
a = torch.rand(N,N, dtype=torch.float32)
x = torch.arange(N, dtype=torch.float32)
%timeit y = a*x

809 µs ± 60.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Now we do the same on gpu 

In [13]:
torch.cuda.is_available()

True

In [14]:
a = torch.rand(N,N, dtype=torch.float32, device="cuda")
x = torch.arange(N, dtype=torch.float32, device="cuda")
%timeit y = a*x

127 µs ± 2.67 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


(pytorch binaries already include CUDA, CuDNN, NCCL, MKL, etc. - but you need to have Nvidia driver installed)

**Attention: from cuda to numpy**
1. bring tensor to cpu with `.cpu()`
2. then call `.numpy()`

In [15]:
y = a*x

In [16]:
#y.numpy()

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [17]:
y.cpu().numpy()

array([[0.00000000e+00, 8.47667038e-01, 9.70036864e-01, ...,
        5.83619751e+02, 8.89175903e+02, 1.15892044e+02],
       [0.00000000e+00, 2.76412398e-01, 1.22722471e+00, ...,
        1.75498138e+02, 8.78239014e+02, 9.45720337e+02],
       [0.00000000e+00, 3.22977006e-01, 1.98101211e+00, ...,
        1.48793655e+02, 6.27703613e+02, 2.54500229e+02],
       ...,
       [0.00000000e+00, 4.28057730e-01, 9.21844661e-01, ...,
        8.97595825e+02, 5.86440918e+02, 9.10931885e+02],
       [0.00000000e+00, 9.28996563e-01, 1.85661256e+00, ...,
        8.38728088e+02, 6.05917786e+02, 6.31650757e+02],
       [0.00000000e+00, 1.14527941e-01, 1.42226708e+00, ...,
        1.75077759e+02, 3.80753593e+01, 3.76903900e+02]], dtype=float32)